sudo: false

language: latex

# cache:
#   directories:
#   - OpAlg_WS15/
  
before_install: 
- wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
- tar -xzf install-tl-unx.tar.gz
- ls
# - chmod +x install-tl
# - ./install-tl --help
  
install: true

script: echo done