sudo: required

language: latex

services:
  - docker
  
before_install:
  - sudo docker build -t texlive docker
  
install: true

script:
  - sudo docker run -it -v ./OpAlg_WS15/:/var/texlive texlive sh -c "latexmk -pdflatex="xelatex --shell-escape %O %S" -pdf -dvi- -ps- -cd -f -interaction=nonstopmode operatoralgebren.tex"
