sudo: false

language: perl

# cache:
#   directories:
#   - OpAlg_WS15/
  
install:
- wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
- tar -xzf install-tl-unx.tar.gz
- cd install-tl-2*
- mv ../texlive.profile texlive.profile 
- ls -a
- chmod +x install-tl
- ./install-tl -profile texlive.profile
- latexmk --help

cache:
  directories:
  - ~

script: echo done