sudo: false

language: latex

# cache:
#   directories:
#   - OpAlg_WS15/
  
before_install: 
	- wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
	- ls
  
install: true

script: echo done